# Generated by Django 3.0.5 on 2020-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='descricao',
            field=models.TextField(default=1, max_length=200, verbose_name='Descricao'),
            preserve_default=False,
        ),
    ]
